version: "3.8"

x-default-app: &default-app
  build:
    context: .
    dockerfile: ./docker/Dockerfile
    target: dev
  env_file:
    - ./docker/.env
  volumes:
    - .:/app
  stdin_open: true
  tty: true

services:
  fastapi:
    <<: *default-app
    container_name: oak-signs-api
    ports:
      - 8004:8004

  mongodb:
    container_name: oak-signs-db
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: notifications
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017

  redis:
    container_name: oak-signs-redis
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  redis-consumer:
    <<: *default-app
    container_name: oak-signs-redis-consumer
    command: python oak_signs/events/consumer.py
