name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  ci:
    name: Lint and Test
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: mongodb://mongo:mongo@localhost:27017/notifications?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: notifications
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: mongo
        ports:
          - 27017:27017
      redis:
        image: "redis:alpine"
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs

      - name: Load cached Poetry venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Pre-commit cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Run pre-commit hooks
        run: make lint

      - name: Run tests with pytest
        run: make test
